version: '3'

services:
  mysql:
    image: "mysql:8.0.25"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=optuna
    ports:
      - "3306:3306"
  postgresql:
    image: "postgres:12.10"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=optuna
    ports:
      - "5432:5432"
  redis:
    image: "redis:6.2.6"
    command: "redis-server"
    ports:
      - "6379:6379"
  optuna-210:
    build:
      context: .
      dockerfile: ./docker/optuna-210/Dockerfile
    volumes:
      - ./src:/work/src
      - ./data:/work/data
  optuna-300:
    build:
      context: .
      dockerfile: ./docker/optuna-300/Dockerfile
    volumes:
      - ./src:/work/src
      - ./data:/work/data