version: '3'

services:
  mysql:
    image: "mysql:8.0.25"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=optuna
    ports:
      - "3306:3306"
    platform: linux/x86_64
  postgresql:
    image: "postgres:12.10"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=optuna
    ports:
      - "5432:5432"
    platform: linux/x86_64
  optuna-210:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./docker/optuna-210/Dockerfile
    volumes:
      - ./src:/work/src
      - ./data:/work/data
  optuna-300b:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/optuna-300b/Dockerfile
    volumes:
      - ./src:/work/src
      - ./data:/work/data
  optuna-303:
    platform: linux/amd64
    build:
      context: .
      dockerfile: docker/optuna-303/Dockerfile
    volumes:
      - ./src:/work/src
      - ./data:/work/data
